spring.application.name=medpro

# Corrigido:
spring.datasource.url=jdbc:mysql://localhost:3306/medpro_api
spring.datasource.username=root
spring.datasource.password=123456

# Recomendações adicionais:
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
